"""
Django settings for KingI project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vpqnd(g%*l$z9f0mom%^l16v=e_u^c+0gnrcs6i_z$lb*mwbj('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# APP模块 =====================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "user",
]

# 中间件 =====================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# 路由 =====================================================
ROOT_URLCONF = 'KingI.urls'


# 模板路径 =====================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KingI.wsgi.application'


# 数据库 =====================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 基本设置 =====================================================
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans' # admin 汉语

TIME_ZONE = 'Asia/Shanghai' # 时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# (CSS, JavaScript, Images)=====================================================
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/STATIC/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "STATIC"),
)

TEMPLATE_DIRS = (os.path.join(BASE_DIR,  'templates'),)


# session 系统默认配置 =====================================================
# SESSION_COOKIE_NAME = "sessionid"          # session ID
# SESSION_COOKIE_PATH = "/"                  # 生效路径
# SESSION_COOKIE_DOMAIN = None               # 生效域名
# SESSION_COOKIE_SECURE = False              # 是否HTTP传输cookie
# SESSION_COOKIE_HTTPONLY = True             # 是否只支持HTTP传输cookie
# SESSION_COOKIE_AGE = 1209600               # 生效时长
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False    # 关闭浏览器session失效
# SESSION_SAVE_EVERY_REQUEST = False         # 每次请求都会保存session

# session  保存到缓存---------------------------------------
# SESSION_ENGING = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# session  保存到文件---------------------------------------
# SESSION_ENGING = "django.contrib.sessions.backends.file"
# SESSION_FILE_PATH = os.path.join(BASE_DIR,"cache")


# 缓存到本地文件 ============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR,'CACHE'),
    }
}